Be in-place operations for mutable variables, when the variables are used as arguments of a function.  It will sometimes cause unexpected behavior both inside and outside of the function.  

Non in-place operations affect nothing outside a function.  It makes a copy of the original object: 

In [9]:
%reset -f
import numpy as np
def func(b):
    print("#1", id(b))
    b = b + 1
    print("#1", id(b))

a = np.arange(5)
func(a)
print(a)

#1 2236985511056
#1 2237009940080
[0 1 2 3 4]


However, in-place operations for mutable arguments change their contents:

In [2]:
%reset -f
import numpy as np

def func(b):
    b += 777

a = np.arange(5)
func(a)
print(a)

[777 778 779 780 781]


Operations on an element of a mutable object is regarded as in-place:

In [3]:
%reset -f
import numpy as np

def func(b):
    print("#1", id(b[1]))
    b[1] = b[1] + 777
    print("#2", id(b[1]))

a = np.arange(5)
func(a)
print(a)

#1 2236988632432
#2 2236988632432
[  0 778   2   3   4]


If you do not want to have any effects outside a function, a quick way is just to make a copy of the argument: 

In [4]:
%reset -f
import numpy as np
import copy

def func(b):
    b = copy.deepcopy(b)
    b[1] = b[1] + 777

a = np.arange(5)
func(a)
print(a)

[0 1 2 3 4]


If an argument is an immutable object, "in-place" operations have no effects outside of a function. (Double quotation on the word in-place, because it is actually not in-place)

In [5]:
%reset -f

def func(b):
    print("#1", id(b))
    b += 7    # creates a new object 
    print("#2", id(b))  

a = 5
func(a)
print(a)

#1 2236911675824
#2 2236911676048
5


Now, let us change the subject a little bit, and consider the effects of in-place operations on default arguments.  Note that default arguments are made when the function is defined, not when it is run. If you perform in-place operations on default mutable objects, the effects of the operations are stored in the function.  Look at the example:

In [6]:
%reset -f
import numpy as np

def func(a, b=np.array([7])):
    a = a + b
    b += 10
    return a
    
a = np.arange(5)
print("#1",a)
a = func(a)
print("#2",a)  # increased by 7
a = func(a)
print("#3",a)  # increased by 17
a = func(a)
print("#4",a)  # increased by 27

#1 [0 1 2 3 4]
#2 [ 7  8  9 10 11]
#3 [24 25 26 27 28]
#4 [51 52 53 54 55]


A quick way to avoid this problem is, again, to make a copy: 

In [7]:
%reset -f
import numpy as np
import copy

def func(a, b=np.array([7])):
    b = copy.deepcopy(b)
    a = a + b
    b += 10
    return a
    
a = np.arange(5)
print("#1",a)
a = func(a)
print("#2",a)  
a = func(a)
print("#3",a) 
a = func(a)
print("#4",a)  

#1 [0 1 2 3 4]
#2 [ 7  8  9 10 11]
#3 [14 15 16 17 18]
#4 [21 22 23 24 25]


Just to be sure, operations on immutable objects have no effects outside of the function: 

In [8]:
%reset -f
import numpy as np

def func(a, b=7):
    a = a + b
    b += 10
    return a
    
a = np.arange(5)
print("#1",a)
a = func(a)
print("#2",a)
a = func(a)
print("#3",a)
a = func(a)
print("#4",a)

#1 [0 1 2 3 4]
#2 [ 7  8  9 10 11]
#3 [14 15 16 17 18]
#4 [21 22 23 24 25]
